// Friendly, plain-language name + description per sus_* function, in PT/EN/ES.
// Overlays the technical roxygen title/description from functions.json (regenerated by
// scripts/build-catalog.mjs) so this survives re-running that script. See catalog/index.ts
// (friendlyName/friendlyDescription) for the fallback rule when a function isn't listed here.

export interface FriendlyText { name: string; description: string }
export type FriendlyEntry = { pt: FriendlyText; en: FriendlyText; es: FriendlyText }

export const FRIENDLY: Record<string, FriendlyEntry> = {
  "sus_climate_aggregate": {
    pt: { name: "Cruzar dados de saúde e clima", description: "Junta os registros de saúde com os dados climáticos ao longo do tempo, aplicando janelas, defasagens (lags) e limiares para preparar a base que vai alimentar a análise epidemiológica." },
    en: { name: "Combine health and climate data", description: "Merges health records with climate data over time, applying time windows, lags and thresholds to build the dataset used in the epidemiological analysis." },
    es: { name: "Cruzar datos de salud y clima", description: "Une los registros de salud con los datos climáticos en el tiempo, aplicando ventanas, rezagos (lags) y umbrales para preparar la base que alimentará el análisis epidemiológico." },
  },
  "sus_climate_anomaly": {
    pt: { name: "Calcular anomalias climáticas", description: "Compara os dados observados nas estações do INMET com as normais climatológicas de 30 anos, calculando o quanto a temperatura, chuva ou outra variável ficou acima ou abaixo do esperado (anomalia absoluta, relativa ou em z-score)." },
    en: { name: "Calculate climate anomalies", description: "Compares observed INMET station data against 30-year climatological normals, calculating how far temperature, rainfall or another variable deviated from the expected value (absolute, relative or z-score anomaly)." },
    es: { name: "Calcular anomalías climáticas", description: "Compara los datos observados en las estaciones del INMET con las normales climatológicas de 30 años, calculando cuánto se desvió la temperatura, la lluvia u otra variable de lo esperado (anomalía absoluta, relativa o en z-score)." },
  },
  "sus_climate_compute_coldwaves": {
    pt: { name: "Detectar ondas de frio", description: "Identifica períodos de onda de frio nos dados climáticos usando sete metodologias reconhecidas (OMS, OMM, INMET, ECF, UTCI, WBGT, HI), útil para relacionar esses eventos a agravos de saúde." },
    en: { name: "Detect cold waves", description: "Identifies cold wave periods in the climate data using seven recognized methods (WHO, WMO, INMET, ECF, UTCI, WBGT, HI), useful for linking these events to health outcomes." },
    es: { name: "Detectar olas de frío", description: "Identifica períodos de ola de frío en los datos climáticos usando siete metodologías reconocidas (OMS, OMM, INMET, ECF, UTCI, WBGT, HI), útil para relacionar estos eventos con problemas de salud." },
  },
  "sus_climate_compute_heatwaves": {
    pt: { name: "Detectar ondas de calor", description: "Identifica períodos de onda de calor nos dados climáticos usando sete metodologias reconhecidas (OMS, OMM, INMET, EHF, UTCI, WBGT, HI), útil para relacionar esses eventos a agravos de saúde." },
    en: { name: "Detect heat waves", description: "Identifies heat wave periods in the climate data using seven recognized methods (WHO, WMO, INMET, EHF, UTCI, WBGT, HI), useful for linking these events to health outcomes." },
    es: { name: "Detectar olas de calor", description: "Identifica períodos de ola de calor en los datos climáticos usando siete metodologías reconocidas (OMS, OMM, INMET, EHF, UTCI, WBGT, HI), útil para relacionar estos eventos con problemas de salud." },
  },
  "sus_climate_compute_indicators": {
    pt: { name: "Calcular índices de conforto térmico", description: "Calcula índices bioclimáticos e de estresse térmico (sensação térmica, conforto e risco de calor/frio) a partir dos dados meteorológicos, para usar como variáveis de exposição na análise de saúde." },
    en: { name: "Calculate thermal comfort indices", description: "Calculates bioclimatic and thermal stress indices (heat index, comfort and heat/cold risk measures) from the meteorological data, for use as exposure variables in the health analysis." },
    es: { name: "Calcular índices de confort térmico", description: "Calcula índices bioclimáticos y de estrés térmico (sensación térmica, confort y riesgo de calor/frío) a partir de los datos meteorológicos, para usarlos como variables de exposición en el análisis de salud." },
  },
  "sus_climate_compute_spei": {
    pt: { name: "Calcular índice de seca (SPEI)", description: "Calcula o Índice Padronizado de Precipitação e Evapotranspiração (SPEI), que combina chuva e temperatura para medir a intensidade da seca em diferentes escalas de tempo." },
    en: { name: "Calculate drought index (SPEI)", description: "Calculates the Standardized Precipitation-Evapotranspiration Index (SPEI), which combines rainfall and temperature to measure drought intensity at different time scales." },
    es: { name: "Calcular índice de sequía (SPEI)", description: "Calcula el Índice Estandarizado de Precipitación y Evapotranspiración (SPEI), que combina lluvia y temperatura para medir la intensidad de la sequía en distintas escalas de tiempo." },
  },
  "sus_climate_compute_spi": {
    pt: { name: "Calcular índice de seca por chuva (SPI)", description: "Calcula o Índice Padronizado de Precipitação (SPI), que usa apenas a chuva para medir a intensidade da seca em diferentes escalas de tempo." },
    en: { name: "Calculate rainfall drought index (SPI)", description: "Calculates the Standardized Precipitation Index (SPI), which uses rainfall alone to measure drought intensity at different time scales." },
    es: { name: "Calcular índice de sequía por lluvia (SPI)", description: "Calcula el Índice Estandarizado de Precipitación (SPI), que utiliza solo la lluvia para medir la intensidad de la sequía en distintas escalas de tiempo." },
  },
  "sus_climate_inmet": {
    pt: { name: "Importar dados das estações do INMET", description: "Baixa e organiza os dados meteorológicos das estações do INMET (Instituto Nacional de Meteorologia) para os anos e estados escolhidos, prontos para cruzar com dados de saúde." },
    en: { name: "Import INMET station data", description: "Downloads and organizes meteorological data from INMET (Brazil's National Institute of Meteorology) weather stations for the chosen years and states, ready to combine with health data." },
    es: { name: "Importar datos de estaciones del INMET", description: "Descarga y organiza los datos meteorológicos de las estaciones del INMET (Instituto Nacional de Meteorología de Brasil) para los años y estados elegidos, listos para cruzar con datos de salud." },
  },
  "sus_climate_normals": {
    pt: { name: "Baixar normais climatológicas do INMET", description: "Baixa as normais climatológicas de 30 anos do INMET (períodos 1961-1990, 1981-2010 ou 1991-2020), usadas como referência para calcular anomalias de clima." },
    en: { name: "Download INMET climate normals", description: "Downloads 30-year climatological normals from INMET (1961-1990, 1981-2010 or 1991-2020 periods), used as the reference for calculating climate anomalies." },
    es: { name: "Descargar normales climáticas del INMET", description: "Descarga las normales climatológicas de 30 años del INMET (períodos 1961-1990, 1981-2010 o 1991-2020), utilizadas como referencia para calcular anomalías climáticas." },
  },
  "sus_climate_normals_meta": {
    pt: { name: "Consultar variáveis das normais climáticas", description: "Mostra a lista de variáveis climáticas disponíveis nas normais do INMET, para você escolher qual usar antes de baixar os dados." },
    en: { name: "Browse climate normals variables", description: "Shows the list of climate variables available in the INMET normals, so you can choose which one to use before downloading the data." },
    es: { name: "Consultar variables de las normales climáticas", description: "Muestra la lista de variables climáticas disponibles en las normales del INMET, para elegir cuál usar antes de descargar los datos." },
  },
  "sus_climate_plot_aggregate": {
    pt: { name: "Visualizar dados de clima e saúde", description: "Gera gráficos que mostram a relação entre o desfecho de saúde escolhido e as variáveis climáticas, incluindo defasagens (lags), para ajudar a interpretar o cruzamento antes de modelar." },
    en: { name: "Visualize climate-health data", description: "Generates charts showing the relationship between the chosen health outcome and the climate variables, including lags, to help interpret the combined data before modeling." },
    es: { name: "Visualizar datos de clima y salud", description: "Genera gráficos que muestran la relación entre el resultado de salud elegido y las variables climáticas, incluyendo rezagos (lags), para ayudar a interpretar el cruce antes de modelar." },
  },
  "sus_climate_plot_coldwaves": {
    pt: { name: "Visualizar ondas de frio", description: "Gera gráficos dos eventos de onda de frio detectados, mostrando sua duração e intensidade ao longo do tempo." },
    en: { name: "Visualize cold waves", description: "Generates charts of the detected cold wave events, showing their duration and intensity over time." },
    es: { name: "Visualizar olas de frío", description: "Genera gráficos de los eventos de ola de frío detectados, mostrando su duración e intensidad a lo largo del tiempo." },
  },
  "sus_climate_plot_fill": {
    pt: { name: "Visualizar preenchimento de falhas climáticas", description: "Mostra em um gráfico como as falhas (dados ausentes) da série climática foram preenchidas, comparando os dados originais com os dados completados." },
    en: { name: "Visualize climate gap-filling", description: "Shows in a chart how gaps (missing data) in the climate series were filled, comparing the original data against the completed data." },
    es: { name: "Visualizar el relleno de vacíos climáticos", description: "Muestra en un gráfico cómo se rellenaron los vacíos (datos faltantes) de la serie climática, comparando los datos originales con los datos completados." },
  },
  "sus_climate_plot_heatwaves": {
    pt: { name: "Visualizar ondas de calor", description: "Gera gráficos dos eventos de onda de calor detectados, mostrando sua duração e intensidade ao longo do tempo." },
    en: { name: "Visualize heat waves", description: "Generates charts of the detected heat wave events, showing their duration and intensity over time." },
    es: { name: "Visualizar olas de calor", description: "Genera gráficos de los eventos de ola de calor detectados, mostrando su duración e intensidad a lo largo del tiempo." },
  },
  "sus_climate_uniplu": {
    pt: { name: "Importar dados de chuva (UNIPLU-BR)", description: "Importa o UNIPLU-BR, um conjunto unificado de dados pluviométricos brasileiros, para os anos e estados escolhidos." },
    en: { name: "Import rainfall data (UNIPLU-BR)", description: "Imports UNIPLU-BR, a unified Brazilian rainfall dataset, for the chosen years and states." },
    es: { name: "Importar datos de lluvia (UNIPLU-BR)", description: "Importa el UNIPLU-BR, un conjunto unificado de datos pluviométricos brasileños, para los años y estados elegidos." },
  },
  "sus_data_aggregate": {
    pt: { name: "Agregar dados em série temporal", description: "Transforma registros individuais de casos em contagens ao longo do tempo (diária, semanal, mensal), agrupando por município ou outra variável. É o passo essencial para preparar os dados para modelos de série temporal, como DLNM." },
    en: { name: "Aggregate data into time series", description: "Turns individual case records into counts over time (daily, weekly, monthly), grouped by municipality or another variable. This is the essential step to prepare data for time-series models such as DLNM." },
    es: { name: "Agregar datos en serie temporal", description: "Convierte los registros individuales de casos en conteos a lo largo del tiempo (diario, semanal, mensual), agrupados por municipio u otra variable. Es el paso esencial para preparar los datos para modelos de series temporales como DLNM." },
  },
  "sus_data_cid_select": {
    pt: { name: "Explorar grupos de doenças (CID-10)", description: "Abre uma tela interativa para navegar pelos grupos de doenças e fatores climáticos relacionados, ajudando a escolher os códigos certos para usar no filtro por CID-10." },
    en: { name: "Explore ICD-10 disease groups", description: "Opens an interactive screen to browse disease groups and related climate factors, helping you pick the right codes to use in the ICD-10 filter step." },
    es: { name: "Explorar grupos de enfermedades (CIE-10)", description: "Abre una pantalla interactiva para navegar por los grupos de enfermedades y factores climáticos relacionados, ayudando a elegir los códigos correctos para el filtro por CIE-10." },
  },
  "sus_data_clean_encoding": {
    pt: { name: "Corrigir acentuação e caracteres", description: "Verifica as colunas de texto e corrige problemas comuns de acentuação (como 'São Paulo' aparecendo errado), garantindo que nomes e textos fiquem corretos antes das próximas etapas." },
    en: { name: "Fix text accents and characters", description: "Checks text columns and fixes common accent/character problems (like 'São Paulo' showing up garbled), making sure names and text are correct before the next steps." },
    es: { name: "Corregir acentos y caracteres", description: "Revisa las columnas de texto y corrige problemas comunes de acentuación (como 'São Paulo' apareciendo mal), garantizando que los nombres y textos queden correctos antes de las siguientes etapas." },
  },
  "sus_data_create_variables": {
    pt: { name: "Criar variáveis derivadas", description: "Cria automaticamente variáveis úteis para a análise, como faixas etárias, variáveis de calendário (dia da semana, estação do ano) e variáveis climáticas, a partir dos dados de saúde (SIM, SINAN, SIH, SIA, SINASC, CNES)." },
    en: { name: "Create derived variables", description: "Automatically creates variables useful for analysis, such as age groups, calendar variables (weekday, season) and climate-related variables, from health data (SIM, SINAN, SIH, SIA, SINASC, CNES)." },
    es: { name: "Crear variables derivadas", description: "Crea automáticamente variables útiles para el análisis, como grupos de edad, variables de calendario (día de la semana, estación del año) y variables climáticas, a partir de los datos de salud (SIM, SINAN, SIH, SIA, SINASC, CNES)." },
  },
  "sus_data_export": {
    pt: { name: "Exportar dados processados", description: "Salva os dados já tratados em um arquivo, junto com informações sobre como foram processados, para que a análise possa ser reproduzida depois. Aceita vários formatos, inclusive para dados espaciais." },
    en: { name: "Export processed data", description: "Saves the already-processed data to a file, along with information about how it was processed, so the analysis can be reproduced later. Supports several formats, including spatial data." },
    es: { name: "Exportar datos procesados", description: "Guarda los datos ya tratados en un archivo, junto con información sobre cómo fueron procesados, para que el análisis pueda reproducirse después. Admite varios formatos, incluyendo datos espaciales." },
  },
  "sus_data_filter_cid": {
    pt: { name: "Filtrar por CID-10 ou grupo de doença", description: "Seleciona apenas os registros que correspondem a códigos CID-10 específicos, faixas de códigos, capítulos ou um dos mais de 50 grupos de doenças já definidos, para focar a análise numa condição de saúde." },
    en: { name: "Filter by ICD-10 or disease group", description: "Selects only the records matching specific ICD-10 codes, code ranges, chapters, or one of 50+ predefined disease groups, so the analysis focuses on a particular health condition." },
    es: { name: "Filtrar por CIE-10 o grupo de enfermedad", description: "Selecciona solo los registros que corresponden a códigos CIE-10 específicos, rangos de códigos, capítulos o uno de los más de 50 grupos de enfermedades predefinidos, para enfocar el análisis en una condición de salud." },
  },
  "sus_data_filter_demographics": {
    pt: { name: "Filtrar por características demográficas", description: "Seleciona registros com base em sexo, raça/cor, faixa etária, escolaridade, região ou município, permitindo analisar subgrupos específicos da população junto com o filtro por CID-10." },
    en: { name: "Filter by demographics", description: "Selects records based on sex, race, age range, education level, region, or municipality, letting you analyze specific population subgroups alongside the ICD-10 filter." },
    es: { name: "Filtrar por características demográficas", description: "Selecciona registros según sexo, raza/color, rango de edad, escolaridad, región o municipio, permitiendo analizar subgrupos específicos de la población junto con el filtro por CIE-10." },
  },
  "sus_data_import": {
    pt: { name: "Importar dados do DATASUS", description: "Baixa e prepara dados dos sistemas de informação em saúde do Brasil (SIM, SINAN, SIH, SIA, CNES, SINASC), guardando uma cópia local para acelerar próximos acessos aos mesmos dados." },
    en: { name: "Import DATASUS data", description: "Downloads and prepares data from Brazil's public health information systems (SIM, SINAN, SIH, SIA, CNES, SINASC), keeping a local copy to speed up future access to the same data." },
    es: { name: "Importar datos de DATASUS", description: "Descarga y prepara datos de los sistemas de información en salud de Brasil (SIM, SINAN, SIH, SIA, CNES, SINASC), guardando una copia local para acelerar accesos futuros a los mismos datos." },
  },
  "sus_data_plot_aggregate_map": {
    pt: { name: "Mapear dados agregados por município", description: "Gera um mapa dos municípios coloridos pelos valores agregados dos dados de saúde (por exemplo, número de casos ou taxa por 100 mil habitantes), permitindo visualizar a distribuição geográfica do agravo." },
    en: { name: "Map aggregated data by municipality", description: "Generates a map of municipalities colored by the aggregated health data values (e.g., case counts or rate per 100,000 population), showing the geographic distribution of the outcome." },
    es: { name: "Mapear datos agregados por municipio", description: "Genera un mapa de los municipios coloreados según los valores agregados de los datos de salud (por ejemplo, número de casos o tasa por 100 mil habitantes), mostrando la distribución geográfica del evento." },
  },
  "sus_data_plot_aggregate_ts": {
    pt: { name: "Gerar gráfico de série temporal", description: "Cria gráficos de série temporal dos dados de saúde já agregados, como curva epidêmica, padrão sazonal ou tendência anual, para visualizar como o agravo evolui ao longo do tempo." },
    en: { name: "Plot time-series chart", description: "Creates time-series charts from already-aggregated health data, such as an epidemic curve, seasonal pattern, or annual trend, to visualize how the outcome evolves over time." },
    es: { name: "Generar gráfico de serie temporal", description: "Crea gráficos de serie temporal a partir de datos de salud ya agregados, como curva epidémica, patrón estacional o tendencia anual, para visualizar cómo evoluciona el evento en el tiempo." },
  },
  "sus_data_plot_demographics": {
    pt: { name: "Visualizar perfil demográfico", description: "Gera tabelas e gráficos resumindo o perfil demográfico e de risco climático dos dados de saúde (SIM, SIH, SINAN, CNES, SIA, SINASC), ajudando a entender quem é mais afetado pelo agravo em estudo." },
    en: { name: "Visualize demographic profile", description: "Generates tables and charts summarizing the demographic and climate-risk profile of the health data (SIM, SIH, SINAN, CNES, SIA, SINASC), helping you understand who is most affected by the outcome under study." },
    es: { name: "Visualizar perfil demográfico", description: "Genera tablas y gráficos que resumen el perfil demográfico y de riesgo climático de los datos de salud (SIM, SIH, SINAN, CNES, SIA, SINASC), ayudando a entender quién se ve más afectado por el evento en estudio." },
  },
  "sus_data_quality_report": {
    pt: { name: "Gerar relatório de qualidade dos dados", description: "Analisa todo o histórico de tratamento aplicado aos dados e gera um relatório de qualidade, cobrindo completude, distribuição demográfica, validade das datas, códigos CID-10 e cobertura geográfica." },
    en: { name: "Generate data quality report", description: "Reviews the entire processing history applied to the data and produces a quality report, covering completeness, demographic distribution, date validity, ICD-10 codes, and geographic coverage." },
    es: { name: "Generar informe de calidad de datos", description: "Analiza todo el historial de tratamiento aplicado a los datos y genera un informe de calidad, cubriendo completitud, distribución demográfica, validez de fechas, códigos CIE-10 y cobertura geográfica." },
  },
  "sus_data_read": {
    pt: { name: "Ler dados exportados", description: "Carrega de volta um ou mais arquivos de dados de saúde exportados anteriormente, detectando o formato automaticamente e recuperando também as informações de processamento salvas." },
    en: { name: "Read exported data", description: "Loads back one or more previously exported health data files, automatically detecting the format and also retrieving the saved processing information." },
    es: { name: "Leer datos exportados", description: "Carga de nuevo uno o más archivos de datos de salud exportados anteriormente, detectando el formato automáticamente y recuperando también la información de procesamiento guardada." },
  },
  "sus_data_standardize": {
    pt: { name: "Padronizar nomes e valores", description: "Padroniza os nomes das colunas e os valores das categorias dos dados de saúde do DATASUS, garantindo consistência entre diferentes anos e versões dos sistemas, em português, inglês ou espanhol." },
    en: { name: "Standardize names and values", description: "Standardizes column names and category values in DATASUS health data, ensuring consistency across different years and system versions, in Portuguese, English, or Spanish." },
    es: { name: "Estandarizar nombres y valores", description: "Estandariza los nombres de columnas y los valores de las categorías de los datos de salud de DATASUS, garantizando consistencia entre diferentes años y versiones de los sistemas, en portugués, inglés o español." },
  },
  "sus_data_ts_quality": {
    pt: { name: "Verificar qualidade da série temporal", description: "Avalia a qualidade da série diária de casos por município, identificando lacunas de dados, quebras estruturais abruptas e meses com valores atípicos, ajudando a decidir se a série está pronta para análise." },
    en: { name: "Check time-series quality", description: "Evaluates the quality of the daily case series by municipality, flagging data gaps, abrupt structural breaks, and months with outlier values, helping decide whether the series is ready for analysis." },
    es: { name: "Verificar calidad de la serie temporal", description: "Evalúa la calidad de la serie diaria de casos por municipio, identificando vacíos de datos, quiebres estructurales abruptos y meses con valores atípicos, ayudando a decidir si la serie está lista para el análisis." },
  },
  "sus_grid_chirps": {
    pt: { name: "Importar chuva por satélite (CHIRPS)", description: "Baixa dados de chuva estimados por satélite (CHIRPS) já agregados por município brasileiro, útil onde não há estação meteorológica próxima." },
    en: { name: "Import satellite rainfall (CHIRPS)", description: "Downloads satellite-estimated rainfall data (CHIRPS) already aggregated by Brazilian municipality, useful where no nearby weather station exists." },
    es: { name: "Importar lluvia satelital (CHIRPS)", description: "Descarga datos de lluvia estimados por satélite (CHIRPS) ya agregados por municipio brasileño, útil donde no hay una estación meteorológica cercana." },
  },
  "sus_grid_era5": {
    pt: { name: "Importar clima por satélite (ERA5)", description: "Baixa dados climáticos diários do modelo de reanálise ERA5-Land, agregados por município brasileiro, cobrindo áreas sem estação meteorológica." },
    en: { name: "Import reanalysis climate data (ERA5)", description: "Downloads daily climate data from the ERA5-Land reanalysis model, aggregated by Brazilian municipality, covering areas without a weather station." },
    es: { name: "Importar clima por reanálisis (ERA5)", description: "Descarga datos climáticos diarios del modelo de reanálisis ERA5-Land, agregados por municipio brasileño, cubriendo áreas sin estación meteorológica." },
  },
  "sus_grid_fires": {
    pt: { name: "Importar focos de queimadas", description: "Baixa dados de focos de calor e queimadas por município brasileiro, para relacionar a exposição à fumaça com desfechos de saúde." },
    en: { name: "Import fire hotspot data", description: "Downloads fire hotspot and burning data by Brazilian municipality, to relate smoke exposure to health outcomes." },
    es: { name: "Importar focos de incendios", description: "Descarga datos de focos de calor e incendios por municipio brasileño, para relacionar la exposición al humo con los resultados de salud." },
  },
  "sus_grid_join": {
    pt: { name: "Juntar dados ambientais por município", description: "Junta dados ambientais em grade (como clima, poluição ou queimadas) aos dados de saúde pelo município, preparando a base para análise." },
    en: { name: "Join gridded data by municipality", description: "Joins gridded environmental data (such as climate, pollution or fires) to the health data by municipality, preparing the dataset for analysis." },
    es: { name: "Unir datos ambientales por municipio", description: "Une datos ambientales en cuadrícula (como clima, contaminación o incendios) a los datos de salud por municipio, preparando la base para el análisis." },
  },
  "sus_grid_koppen": {
    pt: { name: "Classificar clima por Köppen", description: "Adiciona a cada município a sua classificação climática de Köppen-Geiger, útil como variável de contexto climático nas análises." },
    en: { name: "Classify climate by Köppen", description: "Adds each municipality's Köppen-Geiger climate classification, useful as a climate context variable in the analysis." },
    es: { name: "Clasificar clima por Köppen", description: "Agrega a cada municipio su clasificación climática de Köppen-Geiger, útil como variable de contexto climático en el análisis." },
  },
  "sus_grid_pdsi": {
    pt: { name: "Importar índice de seca (PDSI)", description: "Baixa o Índice de Severidade de Seca de Palmer (PDSI) por município brasileiro, medida clássica de intensidade e duração da seca." },
    en: { name: "Import drought index (PDSI)", description: "Downloads the Palmer Drought Severity Index (PDSI) by Brazilian municipality, a classic measure of drought intensity and duration." },
    es: { name: "Importar índice de sequía (PDSI)", description: "Descarga el Índice de Severidad de Sequía de Palmer (PDSI) por municipio brasileño, una medida clásica de la intensidad y duración de la sequía." },
  },
  "sus_grid_pollution_cams": {
    pt: { name: "Importar poluição do ar (CAMS)", description: "Baixa dados de poluentes atmosféricos do serviço CAMS (Copernicus) por município, para estudar a relação entre qualidade do ar e saúde." },
    en: { name: "Import air pollution data (CAMS)", description: "Downloads air pollutant data from the CAMS (Copernicus) service by municipality, to study the relationship between air quality and health." },
    es: { name: "Importar contaminación del aire (CAMS)", description: "Descarga datos de contaminantes atmosféricos del servicio CAMS (Copernicus) por municipio, para estudiar la relación entre la calidad del aire y la salud." },
  },
  "sus_grid_pollution_ghap": {
    pt: { name: "Importar poluição do ar de alta resolução (GHAP)", description: "Baixa dados de poluentes atmosféricos em alta resolução do conjunto GHAP por município brasileiro, para estudar a relação entre qualidade do ar e saúde." },
    en: { name: "Import high-resolution air pollution (GHAP)", description: "Downloads high-resolution air pollutant data from the GHAP dataset by Brazilian municipality, to study the relationship between air quality and health." },
    es: { name: "Importar contaminación del aire de alta resolución (GHAP)", description: "Descarga datos de contaminantes atmosféricos de alta resolución del conjunto GHAP por municipio brasileño, para estudiar la relación entre la calidad del aire y la salud." },
  },
  "sus_grid_pollution_merra2": {
    pt: { name: "Importar poluição do ar (MERRA-2)", description: "Baixa dados de poluentes atmosféricos do modelo de reanálise MERRA-2 por município brasileiro, para estudar a relação entre qualidade do ar e saúde." },
    en: { name: "Import air pollution data (MERRA-2)", description: "Downloads air pollutant data from the MERRA-2 reanalysis model by Brazilian municipality, to study the relationship between air quality and health." },
    es: { name: "Importar contaminación del aire (MERRA-2)", description: "Descarga datos de contaminantes atmosféricos del modelo de reanálisis MERRA-2 por municipio brasileño, para estudiar la relación entre la calidad del aire y la salud." },
  },
  "sus_grid_prodes": {
    pt: { name: "Importar dados de desmatamento (PRODES)", description: "Baixa dados de desmatamento por bioma do PRODES/TerraBrasilis por município brasileiro, para relacionar mudanças ambientais a desfechos de saúde." },
    en: { name: "Import deforestation data (PRODES)", description: "Downloads deforestation-by-biome data from PRODES/TerraBrasilis by Brazilian municipality, to relate environmental change to health outcomes." },
    es: { name: "Importar datos de deforestación (PRODES)", description: "Descarga datos de deforestación por bioma del PRODES/TerraBrasilis por municipio brasileño, para relacionar cambios ambientales con resultados de salud." },
  },
  "sus_grid_smvi": {
    pt: { name: "Calcular seca-relâmpago (SMVI)", description: "Calcula o Índice de Volatilidade da Umidade do Solo (SMVI), que identifica secas-relâmpago (de início rápido) por município brasileiro." },
    en: { name: "Calculate flash drought (SMVI)", description: "Calculates the Soil Moisture Volatility Index (SMVI), which identifies fast-onset flash droughts by Brazilian municipality." },
    es: { name: "Calcular sequía relámpago (SMVI)", description: "Calcula el Índice de Volatilidad de la Humedad del Suelo (SMVI), que identifica sequías relámpago (de inicio rápido) por municipio brasileño." },
  },
  "sus_mod_af": {
    pt: { name: "Calcular fração atribuível", description: "A partir de um modelo DLNM já ajustado, calcula a fração e o número de casos (mortes ou internações) atribuíveis ao calor e ao frio, mostrando quanto da carga de saúde está ligada à exposição climática." },
    en: { name: "Calculate attributable fraction", description: "From an already-fitted DLNM, calculates the fraction and number of cases (deaths or hospitalizations) attributable to heat and cold, showing how much of the health burden is linked to climate exposure." },
    es: { name: "Calcular fracción atribuible", description: "A partir de un modelo DLNM ya ajustado, calcula la fracción y el número de casos (muertes u hospitalizaciones) atribuibles al calor y al frío, mostrando cuánta carga de salud está ligada a la exposición climática." },
  },
  "sus_mod_burden": {
    pt: { name: "Ranquear carga de doença por cidade", description: "Reúne os resultados de fração atribuível ou excesso de óbitos de várias cidades numa tabela ranqueada, mostrando quais localidades mais contribuem para a carga total de doença." },
    en: { name: "Rank disease burden by city", description: "Combines attributable-fraction or excess-mortality results from multiple cities into a ranked table, showing which locations contribute most to the total disease burden." },
    es: { name: "Clasificar carga de enfermedad por ciudad", description: "Reúne los resultados de fracción atribuible o exceso de mortalidad de varias ciudades en una tabla clasificada, mostrando qué localidades más contribuyen a la carga total de enfermedad." },
  },
  "sus_mod_casecrossover": {
    pt: { name: "Analisar com case-crossover", description: "Avalia a associação entre uma variável climática e um desfecho de saúde comparando cada período com ele mesmo em datas de controle (mesmo mês ou semana), o que remove automaticamente tendências sazonais de longo prazo." },
    en: { name: "Analyze with case-crossover", description: "Assesses the association between a climate variable and a health outcome by comparing each period to itself on control dates (same month or week), which automatically removes long-term seasonal trends." },
    es: { name: "Analizar con case-crossover", description: "Evalúa la asociación entre una variable climática y un desenlace de salud comparando cada período consigo mismo en fechas de control (mismo mes o semana), lo que elimina automáticamente las tendencias estacionales de largo plazo." },
  },
  "sus_mod_dlnm": {
    pt: { name: "Modelar risco com DLNM", description: "Ajusta um Modelo Não Linear Distribuído no Tempo (DLNM) para quantificar como uma variável climática (ex.: temperatura) afeta um desfecho de saúde ao longo de vários dias de defasagem, captando efeitos que não são imediatos nem lineares." },
    en: { name: "Model risk with DLNM", description: "Fits a Distributed Lag Non-linear Model (DLNM) to quantify how a climate variable (e.g., temperature) affects a health outcome across several days of lag, capturing effects that are neither immediate nor linear." },
    es: { name: "Modelar riesgo con DLNM", description: "Ajusta un Modelo No Lineal Distribuido en el Tiempo (DLNM) para cuantificar cómo una variable climática (p. ej., temperatura) afecta un desenlace de salud a lo largo de varios días de rezago, capturando efectos que no son inmediatos ni lineales." },
  },
  "sus_mod_excess": {
    pt: { name: "Estimar excesso de óbitos", description: "Estima o excesso de óbitos ou internações comparando os valores observados com uma linha de base esperada, calculada a partir do modelo DLNM, de uma curva sazonal (spline) ou do método de Serfling." },
    en: { name: "Estimate excess deaths", description: "Estimates excess deaths or hospitalizations by comparing observed values against an expected baseline, calculated from the DLNM model, a seasonal spline curve, or the Serfling method." },
    es: { name: "Estimar exceso de muertes", description: "Estima el exceso de muertes u hospitalizaciones comparando los valores observados con una línea base esperada, calculada a partir del modelo DLNM, una curva estacional (spline) o el método de Serfling." },
  },
  "sus_mod_its": {
    pt: { name: "Avaliar impacto com série interrompida", description: "Estima o efeito imediato e o efeito duradouro de um evento (política pública, evento extremo, pandemia) sobre uma série diária de saúde, separando a mudança de nível (impacto imediato) da mudança de tendência (impacto ao longo do tempo)." },
    en: { name: "Assess impact with interrupted series", description: "Estimates the immediate and lasting effect of an event (policy, extreme event, pandemic) on a daily health series, separating the level change (immediate impact) from the trend change (impact over time)." },
    es: { name: "Evaluar impacto con serie interrumpida", description: "Estima el efecto inmediato y el efecto duradero de un evento (política pública, evento extremo, pandemia) sobre una serie diaria de salud, separando el cambio de nivel (impacto inmediato) del cambio de tendencia (impacto en el tiempo)." },
  },
  "sus_mod_metaregression": {
    pt: { name: "Explicar diferenças entre cidades", description: "Explica por que o risco climático varia entre cidades, incluindo características locais (temperatura média, pobreza, estrutura etária) como preditoras na meta-análise combinada dos modelos DLNM." },
    en: { name: "Explain differences across cities", description: "Explains why climate risk differs across cities by adding local characteristics (mean temperature, poverty, age structure) as predictors in the pooled DLNM meta-analysis." },
    es: { name: "Explicar diferencias entre ciudades", description: "Explica por qué el riesgo climático varía entre ciudades, incluyendo características locales (temperatura media, pobreza, estructura etaria) como predictoras en el metaanálisis combinado de los modelos DLNM." },
  },
  "sus_mod_ml": {
    pt: { name: "Prever desfechos com machine learning", description: "Treina um modelo de machine learning (XGBoost) para prever desfechos de saúde — casos, óbitos, internações — a partir de variáveis climáticas e socioeconômicas, testando o modelo com validação cruzada." },
    en: { name: "Predict outcomes with machine learning", description: "Trains a machine learning model (XGBoost) to predict health outcomes — cases, deaths, hospitalizations — from climate and socioeconomic variables, testing it with cross-validation." },
    es: { name: "Predecir desenlaces con machine learning", description: "Entrena un modelo de machine learning (XGBoost) para predecir desenlaces de salud — casos, muertes, hospitalizaciones — a partir de variables climáticas y socioeconómicas, evaluándolo con validación cruzada." },
  },
  "sus_mod_plot_af": {
    pt: { name: "Visualizar fração atribuível", description: "Gera gráficos de barras, forest plots e tabelas-resumo a partir de um resultado de fração atribuível, seguindo os padrões de comunicação usados em epidemiologia ambiental." },
    en: { name: "Visualize attributable fraction", description: "Generates bar charts, forest plots, and summary tables from an attributable-fraction result, following standard environmental-epidemiology reporting formats." },
    es: { name: "Visualizar fracción atribuible", description: "Genera gráficos de barras, forest plots y tablas resumen a partir de un resultado de fracción atribuible, siguiendo los formatos estándar de comunicación en epidemiología ambiental." },
  },
  "sus_mod_plot_burden": {
    pt: { name: "Visualizar carga de doença por cidade", description: "Gera gráficos de pontos (lollipop), curvas de Lorenz e gráficos de barras empilhadas a partir de uma tabela de carga de doença por cidade." },
    en: { name: "Visualize disease burden by city", description: "Generates lollipop charts, Lorenz concentration curves, and stacked bar charts from a city-level disease burden table." },
    es: { name: "Visualizar carga de enfermedad por ciudad", description: "Genera gráficos de puntos (lollipop), curvas de Lorenz y gráficos de barras apiladas a partir de una tabla de carga de enfermedad por ciudad." },
  },
  "sus_mod_plot_dlnm": {
    pt: { name: "Visualizar resultados do DLNM", description: "Gera os gráficos e tabelas científicas padrão de um modelo DLNM: curva de exposição-resposta, curva de defasagem, superfície tridimensional e outros formatos usados em publicações da área." },
    en: { name: "Visualize DLNM results", description: "Generates the standard scientific plots and tables for a DLNM fit: overall exposure-response curve, lag-response curve, 3D surface, and other formats used in the field's publications." },
    es: { name: "Visualizar resultados del DLNM", description: "Genera los gráficos y tablas científicas estándar de un modelo DLNM: curva de exposición-respuesta, curva de rezago, superficie tridimensional y otros formatos usados en publicaciones del área." },
  },
  "sus_mod_plot_ml": {
    pt: { name: "Visualizar modelo de machine learning", description: "Gera gráficos de importância das variáveis, dispersão entre valores observados e previstos, e curvas de validação cruzada a partir de um modelo de machine learning." },
    en: { name: "Visualize machine learning model", description: "Generates feature-importance charts, observed-vs-predicted scatter plots, and cross-validation curves from a machine learning model." },
    es: { name: "Visualizar modelo de machine learning", description: "Genera gráficos de importancia de variables, dispersión entre valores observados y predichos, y curvas de validación cruzada a partir de un modelo de machine learning." },
  },
  "sus_mod_plot_pool": {
    pt: { name: "Visualizar meta-análise de DLNM", description: "Gera curvas de exposição-resposta combinadas, forest plots por cidade e gráficos de trajetórias individuais a partir de uma meta-análise de modelos DLNM." },
    en: { name: "Visualize pooled DLNM meta-analysis", description: "Generates pooled exposure-response curves, city-specific forest plots, and individual-trajectory (spaghetti) plots from a pooled DLNM meta-analysis." },
    es: { name: "Visualizar metaanálisis de DLNM", description: "Genera curvas de exposición-respuesta combinadas, forest plots por ciudad y gráficos de trayectorias individuales a partir de un metaanálisis de modelos DLNM." },
  },
  "sus_mod_plot_sensitivity": {
    pt: { name: "Visualizar análise de sensibilidade", description: "Gera sobreposições de curvas de exposição-resposta, gráficos de risco relativo por calor/frio e forest plots agrupados, comparando a sensibilidade entre subgrupos populacionais." },
    en: { name: "Visualize sensitivity analysis", description: "Generates overlaid exposure-response curves, hot-vs-cold relative-risk scatter plots, and grouped forest plots to compare sensitivity across population subgroups." },
    es: { name: "Visualizar análisis de sensibilidad", description: "Genera superposiciones de curvas de exposición-respuesta, gráficos de riesgo relativo por calor/frío y forest plots agrupados, comparando la sensibilidad entre subgrupos poblacionales." },
  },
  "sus_mod_plot_spacetime": {
    pt: { name: "Mapear risco espaço-temporal", description: "Gera mapas de risco relativo, gráficos de tendência temporal, mapas de calor de interação espaço-tempo e mapas de probabilidade de excedência a partir de um modelo Bayesiano espaço-temporal." },
    en: { name: "Map space-time risk", description: "Generates relative-risk choropleth maps, temporal trend charts, space-time interaction heatmaps, and exceedance-probability maps from a Bayesian space-time model." },
    es: { name: "Mapear riesgo espacio-temporal", description: "Genera mapas de riesgo relativo, gráficos de tendencia temporal, mapas de calor de interacción espacio-tiempo y mapas de probabilidad de excedencia a partir de un modelo bayesiano espacio-temporal." },
  },
  "sus_mod_plot_spatial_bayes": {
    pt: { name: "Mapear risco com Bayes espacial", description: "Gera um mapa de risco relativo, um mapa de incerteza (largura do intervalo de credibilidade) e um forest plot de efeitos fixos a partir de um modelo Bayesiano espacial de mapeamento de doença." },
    en: { name: "Map risk with spatial Bayes", description: "Generates a relative-risk choropleth map, an uncertainty map (credible-interval width), and a forest plot of fixed effects from a Bayesian spatial disease-mapping model." },
    es: { name: "Mapear riesgo con Bayes espacial", description: "Genera un mapa de riesgo relativo, un mapa de incertidumbre (ancho del intervalo de credibilidad) y un forest plot de efectos fijos a partir de un modelo bayesiano espacial de mapeo de enfermedad." },
  },
  "sus_mod_plot_spatial_moran": {
    pt: { name: "Visualizar clusters espaciais (Moran)", description: "Gera um mapa de clusters (LISA) e um gráfico de dispersão de Moran para visualizar onde municípios com valores altos ou baixos de um indicador se concentram no espaço." },
    en: { name: "Visualize spatial clusters (Moran)", description: "Generates a LISA cluster map and a Moran scatter plot to visualize where municipalities with high or low values of an indicator cluster together in space." },
    es: { name: "Visualizar clústeres espaciales (Moran)", description: "Genera un mapa de clústeres (LISA) y un gráfico de dispersión de Moran para visualizar dónde se concentran espacialmente los municipios con valores altos o bajos de un indicador." },
  },
  "sus_mod_plot_spatial_scan": {
    pt: { name: "Mapear clusters de Kulldorff", description: "Gera um mapa colorido dos municípios conforme o risco relativo ou o rótulo do cluster identificado pelo escaneamento espacial de Kulldorff, facilitando ver onde estão os agrupamentos de casos." },
    en: { name: "Map Kulldorff scan clusters", description: "Generates a choropleth map of municipalities colored by relative risk or cluster label from the Kulldorff spatial scan, making it easy to see where case clusters are located." },
    es: { name: "Mapear clústeres de Kulldorff", description: "Genera un mapa coloreado de los municipios según el riesgo relativo o la etiqueta de clúster identificado por el escaneo espacial de Kulldorff, facilitando ver dónde se ubican las agrupaciones de casos." },
  },
  "sus_mod_plot_swot": {
    pt: { name: "Visualizar análise SWOT", description: "Gera gráfico radar, matriz 2×2 e gráficos de barras a partir de uma análise SWOT climática, facilitando a comunicação de forças, fraquezas, oportunidades e ameaças para gestores." },
    en: { name: "Visualize SWOT analysis", description: "Generates radar charts, a 2x2 matrix board, and bar charts from a climate-health SWOT analysis, making it easier to communicate strengths, weaknesses, opportunities, and threats to decision-makers." },
    es: { name: "Visualizar análisis SWOT", description: "Genera gráfico radar, matriz 2×2 y gráficos de barras a partir de un análisis SWOT climático, facilitando comunicar fortalezas, debilidades, oportunidades y amenazas a los gestores." },
  },
  "sus_mod_plot_vulnerability": {
    pt: { name: "Visualizar índice de vulnerabilidade", description: "Gera rankings de vulnerabilidade por cidade, decomposição por pilar do IPCC (exposição, sensibilidade, capacidade adaptativa) e curvas de Lorenz a partir de um índice de vulnerabilidade." },
    en: { name: "Visualize vulnerability index", description: "Generates city vulnerability rankings, IPCC-pillar breakdowns (exposure, sensitivity, adaptive capacity), and Lorenz concentration curves from a vulnerability index." },
    es: { name: "Visualizar índice de vulnerabilidad", description: "Genera rankings de vulnerabilidad por ciudad, desglose por pilar del IPCC (exposición, sensibilidad, capacidad adaptativa) y curvas de Lorenz a partir de un índice de vulnerabilidad." },
  },
  "sus_mod_pool": {
    pt: { name: "Combinar DLNM entre cidades", description: "Combina estimativas de modelos DLNM de várias cidades numa única curva de risco climático usando meta-análise multivariada em dois estágios, aumentando a robustez estatística e permitindo comparar cidades." },
    en: { name: "Pool DLNM estimates across cities", description: "Pools DLNM estimates from multiple cities into a single climate-risk curve using two-stage multivariate meta-analysis, increasing statistical robustness and enabling city comparisons." },
    es: { name: "Combinar estimaciones de DLNM entre ciudades", description: "Combina estimaciones de modelos DLNM de varias ciudades en una única curva de riesgo climático mediante metaanálisis multivariado en dos etapas, aumentando la robustez estadística y permitiendo comparar ciudades." },
  },
  "sus_mod_sensitivity": {
    pt: { name: "Comparar sensibilidade entre grupos", description: "Compara curvas de exposição-resposta e risco relativo entre subgrupos populacionais (faixa etária, sexo, renda, município) para identificar quais grupos são mais vulneráveis ao clima." },
    en: { name: "Compare sensitivity across groups", description: "Compares exposure-response curves and relative risk across population subgroups (age group, sex, income, municipality) to identify which groups are most vulnerable to climate." },
    es: { name: "Comparar sensibilidad entre grupos", description: "Compara curvas de exposición-respuesta y riesgo relativo entre subgrupos poblacionales (grupo etario, sexo, ingreso, municipio) para identificar qué grupos son más vulnerables al clima." },
  },
  "sus_mod_spacetime_bayes": {
    pt: { name: "Modelar risco espaço-temporal (Bayes)", description: "Ajusta um modelo Bayesiano hierárquico espaço-temporal (via INLA) para estimar o risco de um desfecho de saúde em cada município e período, considerando simultaneamente a dependência espacial e temporal dos dados." },
    en: { name: "Model space-time risk (Bayesian)", description: "Fits a Bayesian hierarchical space-time model (via INLA) to estimate the risk of a health outcome for each municipality and time period, accounting for both spatial and temporal dependence in the data." },
    es: { name: "Modelar riesgo espacio-temporal (Bayes)", description: "Ajusta un modelo bayesiano jerárquico espacio-temporal (vía INLA) para estimar el riesgo de un desenlace de salud en cada municipio y período, considerando simultáneamente la dependencia espacial y temporal de los datos." },
  },
  "sus_mod_spacetime_exceedance": {
    pt: { name: "Calcular probabilidade de excedência", description: "Calcula, a partir de um modelo Bayesiano espaço-temporal já ajustado, a probabilidade de o risco em cada município e período ultrapassar um limiar definido, útil para priorizar alertas e ações." },
    en: { name: "Calculate exceedance probability", description: "Calculates, from an already-fitted Bayesian space-time model, the probability that risk in each municipality and time period exceeds a defined threshold, useful for prioritizing alerts and actions." },
    es: { name: "Calcular probabilidad de excedencia", description: "Calcula, a partir de un modelo bayesiano espacio-temporal ya ajustado, la probabilidad de que el riesgo en cada municipio y período supere un umbral definido, útil para priorizar alertas y acciones." },
  },
  "sus_mod_spacetime_predict": {
    pt: { name: "Prever risco futuro no espaço-tempo", description: "Gera previsões de risco para novos dados ou períodos futuros a partir de um modelo Bayesiano espaço-temporal já ajustado, incluindo intervalos de incerteza." },
    en: { name: "Predict future space-time risk", description: "Generates risk predictions for new data or future time periods from an already-fitted Bayesian space-time model, including uncertainty intervals." },
    es: { name: "Predecir riesgo futuro espacio-temporal", description: "Genera predicciones de riesgo para nuevos datos o períodos futuros a partir de un modelo bayesiano espacio-temporal ya ajustado, incluyendo intervalos de incertidumbre." },
  },
  "sus_mod_spatial_bayes": {
    pt: { name: "Mapear risco com Bayes espacial (CAR/BYM)", description: "Ajusta um modelo Bayesiano espacial (CAR/BYM) para mapear o risco de doença por município, suavizando estimativas instáveis ao considerar a semelhança com municípios vizinhos e incluindo variáveis climáticas." },
    en: { name: "Map disease risk with spatial Bayes (CAR/BYM)", description: "Fits a Bayesian spatial model (CAR/BYM) to map disease risk by municipality, smoothing unstable estimates by borrowing strength from neighboring municipalities and including climate covariates." },
    es: { name: "Mapear riesgo con Bayes espacial (CAR/BYM)", description: "Ajusta un modelo bayesiano espacial (CAR/BYM) para mapear el riesgo de enfermedad por municipio, suavizando estimaciones inestables al considerar la similitud con municipios vecinos e incluyendo variables climáticas." },
  },
  "sus_mod_spatial_moran": {
    pt: { name: "Testar autocorrelação espacial (Moran)", description: "Testa se um indicador de saúde está espacialmente agrupado entre municípios (Moran global) e identifica onde estão os agrupamentos de valores altos ou baixos (LISA local)." },
    en: { name: "Test spatial autocorrelation (Moran)", description: "Tests whether a health indicator is spatially clustered across municipalities (global Moran's I) and identifies where clusters of high or low values are located (local LISA)." },
    es: { name: "Probar autocorrelación espacial (Moran)", description: "Prueba si un indicador de salud está agrupado espacialmente entre municipios (Moran global) e identifica dónde se ubican los agrupamientos de valores altos o bajos (LISA local)." },
  },
  "sus_mod_spatial_reg": {
    pt: { name: "Modelar regressão espacial", description: "Ajusta modelos de regressão espacial (SAR, SEM, SDM ou SAC) que consideram o efeito de transbordamento entre municípios vizinhos, capturando como o clima em um local pode influenciar a saúde em locais próximos." },
    en: { name: "Model spatial regression", description: "Fits spatial regression models (SAR, SEM, SDM, or SAC) that account for spillover effects between neighboring municipalities, capturing how climate in one area can influence health in nearby areas." },
    es: { name: "Modelar regresión espacial", description: "Ajusta modelos de regresión espacial (SAR, SEM, SDM o SAC) que consideran el efecto de desbordamiento entre municipios vecinos, capturando cómo el clima en un lugar puede influir en la salud de lugares cercanos." },
  },
  "sus_mod_spatial_scan": {
    pt: { name: "Detectar clusters de doença (Kulldorff)", description: "Aplica o teste de escaneamento espacial de Kulldorff para detectar agrupamentos geográficos de excesso de casos, identificando o cluster mais provável e outros clusters secundários significativos." },
    en: { name: "Detect disease clusters (Kulldorff)", description: "Applies the Kulldorff spatial scan statistic to detect geographic clusters of excess disease cases, identifying the most likely cluster and any significant secondary clusters." },
    es: { name: "Detectar clústeres de enfermedad (Kulldorff)", description: "Aplica la prueba de escaneo espacial de Kulldorff para detectar agrupamientos geográficos de exceso de casos, identificando el clúster más probable y otros clústeres secundarios significativos." },
  },
  "sus_mod_spatial_weights": {
    pt: { name: "Construir vizinhança entre municípios", description: "Constrói a matriz de vizinhança entre os municípios a partir dos seus contornos (polígonos), definindo quais são considerados vizinhos. É um passo necessário antes de qualquer análise espacial (Moran, Bayes espacial, regressão espacial)." },
    en: { name: "Build neighborhood weights between municipalities", description: "Builds the neighborhood matrix between municipalities from their boundary polygons, defining which ones are considered neighbors. This is a required step before any spatial analysis (Moran, spatial Bayes, spatial regression)." },
    es: { name: "Construir vecindad entre municipios", description: "Construye la matriz de vecindad entre municipios a partir de sus polígonos de contorno, definiendo cuáles se consideran vecinos. Es un paso necesario antes de cualquier análisis espacial (Moran, Bayes espacial, regresión espacial)." },
  },
  "sus_mod_swot": {
    pt: { name: "Montar análise SWOT climática", description: "Reúne resultados já calculados (vulnerabilidade, fração atribuível, carga de doença, DLNM, sensibilidade) numa análise SWOT — Forças, Fraquezas, Oportunidades e Ameaças — voltada para comunicação de risco climático e planejamento territorial." },
    en: { name: "Build climate-health SWOT analysis", description: "Combines already-computed results (vulnerability, attributable fraction, disease burden, DLNM, sensitivity) into a SWOT framework — Strengths, Weaknesses, Opportunities, Threats — for climate-health risk communication and territorial planning." },
    es: { name: "Elaborar análisis SWOT climático", description: "Reúne resultados ya calculados (vulnerabilidad, fracción atribuible, carga de enfermedad, DLNM, sensibilidad) en un análisis SWOT — Fortalezas, Debilidades, Oportunidades y Amenazas — orientado a la comunicación de riesgo climático y la planificación territorial." },
  },
  "sus_mod_vulnerability_index": {
    pt: { name: "Calcular índice de vulnerabilidade (IPCC)", description: "Constrói um índice composto de vulnerabilidade por cidade seguindo o modelo do IPCC (AR6): Vulnerabilidade = Exposição + Sensibilidade − Capacidade Adaptativa, a partir de indicadores numéricos fornecidos pelo usuário." },
    en: { name: "Calculate vulnerability index (IPCC)", description: "Builds a city-level composite vulnerability index following the IPCC (AR6) framework: Vulnerability = Exposure + Sensitivity − Adaptive Capacity, based on user-supplied numeric indicators." },
    es: { name: "Calcular índice de vulnerabilidad (IPCC)", description: "Construye un índice compuesto de vulnerabilidad por ciudad siguiendo el marco del IPCC (AR6): Vulnerabilidad = Exposición + Sensibilidad − Capacidad Adaptativa, a partir de indicadores numéricos proporcionados por el usuario." },
  },
  "sus_rap_addin_export": {
    pt: { name: "Exportar pipeline selecionado", description: "Pega o pipeline que você selecionou no editor de código e salva como um arquivo pronto para compartilhar ou executar novamente depois." },
    en: { name: "Export selected pipeline", description: "Takes the pipeline you selected in the code editor and saves it as a file ready to share or run again later." },
    es: { name: "Exportar pipeline seleccionado", description: "Toma el pipeline que seleccionaste en el editor de código y lo guarda como un archivo listo para compartir o volver a ejecutar más adelante." },
  },
  "sus_rap_export": {
    pt: { name: "Salvar pipeline para reutilizar", description: "Transforma seu pipeline montado em um arquivo independente (script, relatório ou documento) que guarda tudo o que é preciso para repetir a análise depois, inclusive em outro computador." },
    en: { name: "Save pipeline for reuse", description: "Turns your assembled pipeline into a stand-alone file (script, report, or document) that keeps everything needed to repeat the analysis later, even on another computer." },
    es: { name: "Guardar pipeline para reutilizar", description: "Convierte tu pipeline armado en un archivo independiente (script, informe o documento) que guarda todo lo necesario para repetir el análisis después, incluso en otra computadora." },
  },
  "sus_rap_from_recipe": {
    pt: { name: "Importar pipeline salvo", description: "Carrega um pipeline que foi salvo antes como uma receita compacta, permitindo ajustar parâmetros e, se quiser, já executar a análise na hora." },
    en: { name: "Import saved pipeline", description: "Loads a pipeline that was previously saved as a compact recipe, letting you tweak parameters and optionally run the analysis right away." },
    es: { name: "Importar pipeline guardado", description: "Carga un pipeline que se guardó antes como una receta compacta, permitiendo ajustar parámetros y, si quieres, ejecutar el análisis de inmediato." },
  },
  "sus_rap_gui": {
    pt: { name: "Abrir painel visual do pipeline", description: "Abre uma tela interativa para configurar estado, anos, sistema e nível de agregação, ver o código gerado e executar ou exportar a análise sem escrever código." },
    en: { name: "Open pipeline visual panel", description: "Opens an interactive screen to set state, years, system, and aggregation level, preview the generated code, and run or export the analysis without writing code." },
    es: { name: "Abrir panel visual del pipeline", description: "Abre una pantalla interactiva para configurar estado, años, sistema y nivel de agregación, ver el código generado y ejecutar o exportar el análisis sin escribir código." },
  },
  "sus_rap_inspect": {
    pt: { name: "Conferir ou comparar pipelines", description: "Mostra um resumo organizado de um pipeline salvo. Se você indicar dois, compara lado a lado o que mudou nos parâmetros e nas etapas." },
    en: { name: "Review or compare pipelines", description: "Shows an organized summary of a saved pipeline. If you give it two, it compares them side by side, highlighting what changed in parameters and steps." },
    es: { name: "Revisar o comparar pipelines", description: "Muestra un resumen organizado de un pipeline guardado. Si indicas dos, los compara lado a lado, mostrando qué cambió en los parámetros y las etapas." },
  },
  "sus_rap_make": {
    pt: { name: "Executar pipeline automatizado", description: "Roda o pipeline automatizado gerado anteriormente, podendo processar várias partes ao mesmo tempo para agilizar a análise." },
    en: { name: "Run automated pipeline", description: "Runs the automated pipeline generated earlier, optionally processing several parts at once to speed up the analysis." },
    es: { name: "Ejecutar pipeline automatizado", description: "Ejecuta el pipeline automatizado generado antes, pudiendo procesar varias partes a la vez para agilizar el análisis." },
  },
  "sus_rap_read": {
    pt: { name: "Abrir arquivo de pipeline salvo", description: "Abre um arquivo de pipeline exportado anteriormente, recuperando os parâmetros e as etapas para que você possa conferir, executar de novo ou editar." },
    en: { name: "Open saved pipeline file", description: "Opens a previously exported pipeline file, recovering its parameters and steps so you can review it, run it again, or edit it." },
    es: { name: "Abrir archivo de pipeline guardado", description: "Abre un archivo de pipeline exportado anteriormente, recuperando sus parámetros y etapas para que puedas revisarlo, volver a ejecutarlo o editarlo." },
  },
  "sus_rap_recipe": {
    pt: { name: "Salvar pipeline como receita simples", description: "Guarda os parâmetros e as etapas do seu pipeline em um arquivo pequeno e fácil de ler, ideal para compartilhar com colegas e importar depois." },
    en: { name: "Save pipeline as simple recipe", description: "Saves your pipeline's parameters and steps into a small, easy-to-read file, ideal for sharing with colleagues and importing again later." },
    es: { name: "Guardar pipeline como receta simple", description: "Guarda los parámetros y las etapas de tu pipeline en un archivo pequeño y fácil de leer, ideal para compartir con colegas e importar de nuevo después." },
  },
  "sus_rap_run": {
    pt: { name: "Executar pipeline salvo", description: "Roda de novo a análise guardada em um pipeline salvo. Você pode trocar parâmetros, como estado ou período, antes de executar." },
    en: { name: "Run saved pipeline", description: "Re-runs the analysis stored in a saved pipeline. You can swap parameters, like the state or time period, before running it." },
    es: { name: "Ejecutar pipeline guardado", description: "Vuelve a ejecutar el análisis guardado en un pipeline. Puedes cambiar parámetros, como el estado o el período, antes de ejecutarlo." },
  },
  "sus_rap_targets": {
    pt: { name: "Gerar pipeline automatizado", description: "Cria um arquivo de automação pronto para rodar seu pipeline sozinho, podendo dividir o processamento por estado, ano ou ambos." },
    en: { name: "Generate automated pipeline", description: "Creates an automation file ready to run your pipeline on its own, optionally splitting the processing by state, year, or both." },
    es: { name: "Generar pipeline automatizado", description: "Crea un archivo de automatización listo para ejecutar tu pipeline por sí solo, pudiendo dividir el procesamiento por estado, año o ambos." },
  },
  "sus_rap_template": {
    pt: { name: "Criar novo projeto de análise", description: "Monta uma pasta de projeto pronta para usar, com pipeline automatizado, relatório configurável e, se quiser, controle de versões de pacotes e integração automática no GitHub." },
    en: { name: "Create new analysis project", description: "Sets up a ready-to-use project folder with an automated pipeline, a configurable report, and optionally package version tracking and automatic GitHub integration." },
    es: { name: "Crear nuevo proyecto de análisis", description: "Arma una carpeta de proyecto lista para usar, con pipeline automatizado, informe configurable y, si quieres, control de versiones de paquetes e integración automática con GitHub." },
  },
  "sus_rap_update": {
    pt: { name: "Atualizar parâmetros do pipeline salvo", description: "Altera valores específicos (como estado ou anos) num arquivo de pipeline já exportado, sem precisar refazer tudo do zero. Uma cópia de segurança é criada antes da mudança." },
    en: { name: "Update saved pipeline parameters", description: "Changes specific values (like state or years) in an already exported pipeline file, without having to redo everything from scratch. A backup copy is created before the change." },
    es: { name: "Actualizar parámetros del pipeline guardado", description: "Cambia valores específicos (como estado o años) en un archivo de pipeline ya exportado, sin tener que rehacer todo desde cero. Se crea una copia de seguridad antes del cambio." },
  },
  "sus_socio_compute_indicators": {
    pt: { name: "Calcular indicadores socioeconômicos e de saúde", description: "Calcula indicadores padronizados a partir das colunas do censo já ligadas aos dados de saúde, cobrindo demografia, vulnerabilidade socioeconômica, mortalidade, morbidade, saúde materno-infantil e disponibilidade de serviços de saúde." },
    en: { name: "Calculate socioeconomic and health indicators", description: "Calculates standardized indicators from the census columns already linked to the health data, covering demographics, socioeconomic vulnerability, mortality, morbidity, maternal-child health and health-resource availability." },
    es: { name: "Calcular indicadores socioeconómicos y de salud", description: "Calcula indicadores estandarizados a partir de las columnas del censo ya vinculadas a los datos de salud, cubriendo demografía, vulnerabilidad socioeconómica, mortalidad, morbilidad, salud materno-infantil y disponibilidad de recursos de salud." },
  },
  "sus_socio_list_indicators": {
    pt: { name: "Consultar indicadores disponíveis", description: "Mostra a lista de indicadores socioeconômicos e de saúde disponíveis, com nome, categoria, colunas necessárias e método de incerteza, para escolher antes de calcular." },
    en: { name: "Browse available indicators", description: "Shows the list of available socioeconomic and health indicators, with their name, category, required columns and uncertainty method, to choose from before computing them." },
    es: { name: "Consultar indicadores disponibles", description: "Muestra la lista de indicadores socioeconómicos y de salud disponibles, con su nombre, categoría, columnas necesarias y método de incertidumbre, para elegir antes de calcularlos." },
  },
}
